-- omp.dglasfaserconnection definition

CREATE TABLE `dglasfaserconnection` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `errorTypes` bigint(20) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `ownerBirthDate` date DEFAULT NULL,
  `savedAt` time DEFAULT NULL,
  `sourceId` bigint(20) DEFAULT NULL,
  `tsn` int(11) DEFAULT NULL,
  `type` bigint(20) DEFAULT NULL,
  `unit` int(11) DEFAULT NULL,
  `address_id` bigint(20) DEFAULT NULL,
  `creator_id` bigint(20) DEFAULT NULL,
  `newerVersion_id` bigint(20) DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `contactPhone` varchar(45) DEFAULT NULL,
  `contactEmail` varchar(45) DEFAULT NULL,
  `externalReference` varchar(45) DEFAULT NULL,
  `hasMultipleApartments` varchar(1) DEFAULT NULL,
  `floor` int(11) DEFAULT NULL,
  `apartment` int(11) DEFAULT NULL,
  `status` varchar(45) DEFAULT NULL,
  `isNotified` varchar(1) DEFAULT NULL,
  `reason` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKD67D06E8E1D16512` (`address_id`),
  KEY `FKD67D06E86623E19A` (`newerVersion_id`),
  KEY `FKD67D06E8481975A9` (`creator_id`),
  CONSTRAINT `FKD67D06E8481975A9` FOREIGN KEY (`creator_id`) REFERENCES `yinsuser` (`id`),
  CONSTRAINT `FK_CO_CO` FOREIGN KEY (`newerVersion_id`) REFERENCES `dglasfaserconnection` (`id`),
  CONSTRAINT `FK_CO_SA` FOREIGN KEY (`address_id`) REFERENCES `dglasfaserserviceaddress` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1531465 DEFAULT CHARSET=latin1;


-- omp.yinsuser definition

CREATE TABLE `yinsuser` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `aTime` bigint(20) NOT NULL,
  `acceptedTerms` bit(1) DEFAULT NULL,
  `active` bit(1) DEFAULT NULL,
  `birthDate` datetime DEFAULT NULL,
  `cTime` bigint(20) NOT NULL,
  `countryName` varchar(32) DEFAULT NULL,
  `discount` int(11) NOT NULL,
  `externalNumber` varchar(32) DEFAULT NULL,
  `imageId` int(11) DEFAULT NULL,
  `lTime` bigint(20) NOT NULL,
  `loginEmail` varchar(128) DEFAULT NULL,
  `lostHash` varchar(32) DEFAULT NULL,
  `name` varchar(64) DEFAULT NULL,
  `passwordMd5` varchar(32) DEFAULT NULL,
  `registrationDate` datetime DEFAULT NULL,
  `secret` varchar(64) DEFAULT NULL,
  `timeZone` varchar(255) DEFAULT NULL,
  `tsn` int(11) DEFAULT NULL,
  `uuId` varchar(48) DEFAULT NULL,
  `varInt1` int(11) DEFAULT NULL,
  `varInt2` int(11) DEFAULT NULL,
  `varInt3` int(11) DEFAULT NULL,
  `varRaw1` varchar(1024) DEFAULT NULL,
  `varRaw2` varchar(2048) DEFAULT NULL,
  `varRaw3` varchar(3072) DEFAULT NULL,
  `varText1` varchar(64) DEFAULT NULL,
  `varText2` varchar(128) DEFAULT NULL,
  `varText3` varchar(255) DEFAULT NULL,
  `xTime` bigint(20) NOT NULL,
  `cUserId` bigint(20) DEFAULT NULL,
  `contact_id` bigint(20) DEFAULT NULL,
  `countryId` bigint(20) DEFAULT NULL,
  `image_id` bigint(20) DEFAULT NULL,
  `localeId` bigint(20) DEFAULT NULL,
  `userStatusId` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`,`uuId`),
  UNIQUE KEY `loginEmail` (`loginEmail`),
  UNIQUE KEY `name_2` (`name`),
  KEY `FKBCC37E40839B876A` (`image_id`),
  KEY `FKBCC37E40D4678C5` (`userStatusId`),
  KEY `FKBCC37E402C8513EA` (`contact_id`),
  KEY `FKBCC37E40752EC4F7` (`countryId`),
  KEY `FKBCC37E406906DF1F` (`localeId`),
  KEY `FKBCC37E4039169FE4` (`cUserId`),
  CONSTRAINT `FKBCC37E402C8513EA` FOREIGN KEY (`contact_id`) REFERENCES `yinscontact` (`id`),
  CONSTRAINT `FKBCC37E4039169FE4` FOREIGN KEY (`cUserId`) REFERENCES `yinsuser` (`id`),
  CONSTRAINT `FKBCC37E406906DF1F` FOREIGN KEY (`localeId`) REFERENCES `yinslocale` (`id`),
  CONSTRAINT `FKBCC37E40752EC4F7` FOREIGN KEY (`countryId`) REFERENCES `yinscountry` (`id`),
  CONSTRAINT `FKBCC37E40839B876A` FOREIGN KEY (`image_id`) REFERENCES `yinsdocument` (`id`),
  CONSTRAINT `FKBCC37E40D4678C5` FOREIGN KEY (`userStatusId`) REFERENCES `yinsuserstatus` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1730 DEFAULT CHARSET=latin1;
